# Generated by Django 4.2.3 on 2023-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_location_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="participant_type",
            field=models.CharField(
                blank=True,
                choices=[("teams", "Teams"), ("individial", "Individual")],
                max_length=15,
                null=True,
            ),
        ),
    ]
