# Generated by Django 4.2.3 on 2023-07-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_registration_participant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.event",
            ),
        ),
    ]
