# Generated by Django 4.2.3 on 2023-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_registration_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
