# Generated by Django 4.2.3 on 2023-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_registration_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_email_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
