# Generated by Django 4.2.3 on 2023-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_registration_is_email_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="events/qr_codes"),
        ),
    ]
