# Generated by Django 4.2.3 on 2023-07-15 14:04

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
