# Generated by Django 4.2.3 on 2023-07-30 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="About Us Page Banner",
                    ),
                ),
                ("main_text", models.TextField(verbose_name="Main Text")),
                ("vision", models.TextField(verbose_name="OSSH Vision")),
                ("mission", models.TextField(verbose_name="OSSH Mission")),
                ("objective", models.TextField(verbose_name="OSSH Objective")),
            ],
            options={
                "verbose_name": "About Us Page Content",
                "verbose_name_plural": "About Us Page Content",
            },
        ),
        migrations.CreateModel(
            name="FoundryDataContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="foundry/",
                        verbose_name="Startup Foundry Page Banner",
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Foundry Page Content",
                "verbose_name_plural": "Foundry Page Content",
            },
        ),
        migrations.CreateModel(
            name="IndexData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_text",
                    models.CharField(max_length=2500, verbose_name="Hero Section Text"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        upload_to="index/hero", verbose_name="Hero Section Image"
                    ),
                ),
                (
                    "team_text",
                    models.CharField(max_length=2500, verbose_name="Team Section Text"),
                ),
                (
                    "team_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="index/team",
                        verbose_name="Team Section Image",
                    ),
                ),
                (
                    "section_3_text",
                    models.CharField(max_length=2500, verbose_name="Section 3 Text"),
                ),
                (
                    "section_3_image",
                    models.ImageField(
                        upload_to="index/section_3", verbose_name="Section 3 Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Page Content",
                "verbose_name_plural": "Index Page Content",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=2500)),
                ("skill", models.CharField(max_length=500)),
                ("role", models.CharField(max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="team/members"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndexCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("file", models.ImageField(upload_to="index/carousel")),
                (
                    "index",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.indexdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
