# Generated by Django 4.2.3 on 2023-07-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_text",
                    models.CharField(max_length=2500, verbose_name="Hero Section Text"),
                ),
                (
                    "hero_image",
                    models.ImageField(upload_to="", verbose_name="Hero Section Image"),
                ),
                (
                    "team_text",
                    models.CharField(max_length=2500, verbose_name="Team Section Text"),
                ),
                (
                    "section_3_text",
                    models.CharField(max_length=2500, verbose_name="Section 3 Text"),
                ),
                (
                    "section_3_image",
                    models.ImageField(upload_to="", verbose_name="Section 3 Image"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
