# Generated by Django 4.2.3 on 2023-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutdata",
            name="email",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="OSSH EMAIL"
            ),
        ),
        migrations.AddField(
            model_name="aboutdata",
            name="location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="OSSH Location"
            ),
        ),
    ]
