# Generated by Django 4.2.3 on 2023-07-15 13:21

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_indexmodel_indexdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_text",
                    froala_editor.fields.FroalaField(verbose_name="Main Text"),
                ),
                ("vision", models.TextField(verbose_name="OSSH Vision")),
                ("mission", models.TextField(verbose_name="OSSH Mission")),
                ("objective", models.TextField(verbose_name="OSSH Objective")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
