# Generated by Django 4.2.3 on 2023-07-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_aboutdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutdata",
            options={
                "verbose_name": "About Us Page Content",
                "verbose_name_plural": "About Us Page Content",
            },
        ),
        migrations.AlterModelOptions(
            name="indexdata",
            options={
                "verbose_name": "Index Page Content",
                "verbose_name_plural": "Index Page Content",
            },
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="hero_image",
            field=models.ImageField(
                upload_to="index/hero", verbose_name="Hero Section Image"
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="section_3_image",
            field=models.ImageField(
                upload_to="index/section_3", verbose_name="Section 3 Image"
            ),
        ),
        migrations.CreateModel(
            name="IndexCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="index/carousel")),
                (
                    "index",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.indexdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
