# Generated by Django 4.2.3 on 2023-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_foundrydatacontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdata",
            name="team_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="index/team",
                verbose_name="Team Section Image",
            ),
        ),
    ]
