# Generated by Django 4.2.3 on 2023-07-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_indexdata_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutdata",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="about/",
                verbose_name="About Us Page Banner",
            ),
        ),
        migrations.AddField(
            model_name="foundrydatacontent",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foundry/",
                verbose_name="Startup Foundry Page Banner",
            ),
        ),
    ]
