# Generated by Django 4.2.3 on 2023-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_aboutdata_banner_foundrydatacontent_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexcarouselimage",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexcarouselimage",
            name="text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
