# Generated by Django 4.2.3 on 2023-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="team/member"),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
