# Generated by Django 4.2.3 on 2023-07-16 10:00

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="blog/")),
                ("title", models.CharField(max_length=2500)),
                ("content", froala_editor.fields.FroalaField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
